Reshaping, stacking, squeezing, unsqueezing (changing shape and dimensions of a tensor)

In [1]:
# reshaping -> reshapes an input tensor to a defined shape
import torch
x =torch.arange(1, 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
# add an extra dimension
x_reshape = x.reshape(1, 9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [5]:
x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [7]:
# cahneg the view
z = x.view(1, 9)
z.shape # view shares the memory with the original tensor(same but diff view)

torch.Size([1, 9])

In [8]:
# stack tensors on top
Xstacked = torch.stack([x, x, x, x], dim=0)
Xstacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [9]:
Xstacked = torch.stack([x, x, x, x], dim=1)
Xstacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [12]:
Xstacked = torch.hstack([x, x, x, x])
Xstacked

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
Xstacked = torch.vstack([x, x, x, x])
Xstacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [21]:
#squeeze -> removes all single dimensions from target tensor
x = torch.zeros(2, 1, 2, 1, 2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [18]:
y = torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

Above torch.size is [2, 1, 2, 1, 2]
Now the torch.size is [2,2,2] so it removed 1's

In [19]:
y = torch.squeeze(x, 0)
y, y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [20]:
y = torch.squeeze(x, (1, 2, 3))
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [26]:
print(f"Previous tensor :  {x}")
print(f"\nPrevious shape : {x.shape}")

y = torch.squeeze(x)

print(f"\nNew Tensor : {y}")
print(f"\nNew shape : {y.shape}")

Previous tensor :  tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

Previous shape : torch.Size([2, 1, 2, 1, 2])

New Tensor : tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

New shape : torch.Size([2, 2, 2])


unsqueez -> adds a single dimension to a target tensor at a specific dim.

In [33]:
#unsqueez
print(f"Previous target : {y}")
print(f"\nPrevious shape : {y.shape}")

z = y.unsqueeze(dim=0)

print(f"\nNew tensor : {z}")
print(f"\nNew Shape : {z.shape}")

Previous target : tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

Previous shape : torch.Size([2, 2, 2])

New tensor : tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

New Shape : torch.Size([1, 2, 2, 2])


permute -> rearranges the dimensions of a targe in a sepecified order

In [52]:
#permute -> it returns view of the original tensor with its dimensions changed

perr = torch.rand(size=(224, 224, 3)) # {height,width,color}

#permuting

permutedd = perr.permute(2, 0, 1)
print(f"Previous shape : {perr.shape}")
print(f"\nNew shape : {permutedd.shape}") # {color,height,width}


Previous shape : torch.Size([224, 224, 3])

New shape : torch.Size([3, 224, 224])


Indexing -> similar to indexing in NumPy

In [53]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x,x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [51]:
#indexing
print(f"print 0th index : {x[0]}")
print(f"\nprint 1th index : {x[0, 1]}")
print(f"\nprint 2ndth index : {x[0, 2, 2]}")
print(f"\nprint all elements with index 1 of the 2nd dimension : {x[:, :, 1]}")

print 0th index : tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

print 1th index : tensor([4, 5, 6])

print 2ndth index : 9

print all elements with index 1 of the 2nd dimension : tensor([[2, 5, 8]])


PyTorch & Numpy :

When converting from numpy to pytorch the default dtype of numpy is float 64 but for pytorch its float32

array = numpy type
tesor = pytorch type

we can change arrray -> tensor
or tensor -> array

In [57]:
# numpy to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [58]:
array =array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [60]:
# Tensor= 32 to NumPy=64

tensor = torch.ones(7)
np_tnsr = tensor.numpy()
tensor, np_tnsr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility -> trying to take random out of random

In [65]:
#reproducibility = reduce the randomness of neural network  using random seed
import torch

ranA = torch.rand(3, 3)
ranB = torch.rand(3, 3)

print(ranA)
print(ranB)
print(ranA == ranB)


tensor([[0.6778, 0.0222, 0.6122],
        [0.0849, 0.2094, 0.2137],
        [0.3597, 0.0273, 0.7122]])
tensor([[0.4794, 0.9247, 0.8092],
        [0.8667, 0.1040, 0.5762],
        [0.0322, 0.8979, 0.0759]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [66]:
# making random but reproducibile tensors [manual_seed]

import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
ranC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
ranD = torch.rand(3, 4)

print(ranC)
print(ranD)
print(ranC == ranD) #flavouring the randomness

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Running tensors and pytorch on GPU for Fast Computing**

Fast computing = CUDA + NVIDIA Hardware + PyTorch